--Connect GRHUM--------------------
-- Create the user 
create user GRILLE_ENS
  identified by "GRILLE_ENS"
  default tablespace USERS
  temporary tablespace TEMP
  profile DEFAULT;
-- Grant/Revoke role privileges 
grant connect to GRILLE_ENS;
grant resource to GRILLE_ENS;
-- Grant/Revoke system privileges 
grant alter any trigger to GRILLE_ENS;
grant change notification to GRILLE_ENS;
grant create table to GRILLE_ENS;
grant create view to GRILLE_ENS;
grant debug connect session to GRILLE_ENS;
grant unlimited tablespace to GRILLE_ENS;

--Droits--------------------------------
--GRHUM---------------------------------
GRANT REFERENCES,SELECT ON  "GRHUM"."STRUCTURE_ULR" TO "GRILLE_ENS";
GRANT EXECUTE ON  "GRHUM"."INS_GROUPE" TO "GRILLE_ENS";
GRANT REFERENCES,SELECT,INSERT ON  "GRHUM"."TYPE_GROUPE" TO "GRILLE_ENS";
GRANT REFERENCES,SELECT,INSERT ON  "GRHUM"."REPART_TYPE_GROUPE" TO "GRILLE_ENS";
GRANT REFERENCES,SELECT ON  GRHUM.v_personnel_actuel_ens TO "GRILLE_ENS";
grant select,references on grhum.rne to grille_ens;
grant select,references on accords.contrat to grille_ens;
grant select,references on grhum.position to grille_ens;
grant select,references on grhum.type_decharge_service to grille_ens;
GRANT REFERENCES,SELECT ON EDTSCOL.reservation to grille_ens;
GRANT REFERENCES,SELECT ON EDTSCOL.reservation_ap to grille_ens;
GRANT REFERENCES,SELECT,INSERT,UPDATE,DELETE ON EDTSCOL.hcomp_recup to grille_ens;
GRANT SELECT ON Edtscol.Hcomp_Recup_Seq TO Grille_Ens;
GRANT REFERENCES,SELECT,UPDATE ON EDTSCOL.periodicite to grille_ens;
GRANT REFERENCES,SELECT ON EDTSCOL.occupant to grille_ens;

--SCOL----------------------------------
GRANT SELECT,REFERENCES ON  "SCOLARITE"."SCOL_FORMATION_DIPLOME" TO "GRILLE_ENS";
GRANT SELECT,REFERENCES ON  "SCOLARITE"."SCOL_FORMATION_ANNEE" TO "GRILLE_ENS";
GRANT SELECT,REFERENCES ON  "SCOLARITE"."SCOL_FORMATION_DISCIPLINE" TO "GRILLE_ENS";
GRANT SELECT,REFERENCES ON  "SCOLARITE"."SCOL_FORMATION_DOMAINE" TO "GRILLE_ENS";
GRANT SELECT,REFERENCES ON  "SCOLARITE"."SCOL_FORMATION_GRADE" TO "GRILLE_ENS";
GRANT SELECT,REFERENCES ON  "SCOLARITE"."SCOL_FORMATION_HABILITATION" TO "GRILLE_ENS";
GRANT SELECT,REFERENCES ON  "SCOLARITE"."SCOL_FORMATION_SPECIALISATION" TO "GRILLE_ENS";
GRANT SELECT,REFERENCES ON  "SCOLARITE"."SCOL_MAQUETTE_AP" TO "GRILLE_ENS";
GRANT SELECT,REFERENCES ON  "SCOLARITE"."SCOL_MAQUETTE_EC" TO "GRILLE_ENS";
GRANT SELECT,REFERENCES ON  "SCOLARITE"."SCOL_MAQUETTE_PARCOURS" TO "GRILLE_ENS";
GRANT SELECT,REFERENCES ON  "SCOLARITE"."SCOL_MAQUETTE_REPARTITION_AP" TO "GRILLE_ENS";
GRANT SELECT,REFERENCES ON  "SCOLARITE"."SCOL_MAQUETTE_REPARTITION_EC" TO "GRILLE_ENS";
GRANT SELECT,REFERENCES ON  "SCOLARITE"."SCOL_MAQUETTE_REPARTITION_SEM" TO "GRILLE_ENS";
GRANT SELECT,REFERENCES ON  "SCOLARITE"."SCOL_MAQUETTE_REPARTITION_UE" TO "GRILLE_ENS";
GRANT SELECT,REFERENCES ON  "SCOLARITE"."SCOL_MAQUETTE_SEMESTRE" TO "GRILLE_ENS";
GRANT SELECT,REFERENCES ON  "SCOLARITE"."SCOL_MAQUETTE_UE" TO "GRILLE_ENS";
grant select,references on scolarite.scol_maquette_horaire_code to grille_ens;

--GRHUM + MANGUE----------------------------
GRANT SELECT,REFERENCES ON  "GRHUM"."CORPS" TO "GRILLE_ENS";
GRANT SELECT,REFERENCES ON  "GRHUM"."GRADE" TO "GRILLE_ENS";
GRANT SELECT,REFERENCES ON  "GRHUM"."INDIVIDU_ULR" TO "GRILLE_ENS";
GRANT SELECT,REFERENCES ON  "MANGUE"."AFFECTATION" TO "GRILLE_ENS";
GRANT SELECT,REFERENCES ON  "MANGUE"."CARRIERE" TO "GRILLE_ENS";
GRANT SELECT,REFERENCES ON  "MANGUE"."CONTRAT" TO "GRILLE_ENS";
GRANT SELECT,REFERENCES ON  "MANGUE"."CONTRAT_AVENANT" TO "GRILLE_ENS";
GRANT SELECT,REFERENCES ON  "MANGUE"."DECHARGE" TO "GRILLE_ENS";
GRANT SELECT,REFERENCES ON  "MANGUE"."ELEMENT_CARRIERE" TO "GRILLE_ENS";
grant select,references on mangue.changement_position to grille_ens;

--HCOMP2-------------------------------------------------------
GRANT SELECT ON  "HCOMP2"."V_HCOMP_EC_CHARGES_AP" TO "GRILLE_ENS";





