SELECT ACT.*
FROM SCOLARITE.SCOL_MAQUETTE_AP AP, SCOLARITE.SCOL_MAQUETTE_EC EC, SCOLARITE.SCOL_MAQUETTE_UE UE,
    SCOLARITE.SCOL_MAQUETTE_PARCOURS PAR, SCOLARITE.SCOL_FORMATION_SPECIALISATION S, 
    SCOLARITE.SCOL_FORMATION_DIPLOME D, SCOLARITE.SCOL_FORMATION_GRADE G, SCOLARITE.SCOL_FORMATION_HABILITATION H,
    GRILLE_ENS.ACTIVITE ACT,GRILLE_ENS.VOEUX V,SCOLARITE.SCOL_MAQUETTE_REPARTITION_AP RAP
    WHERE V.MAP_KEY = RAP.MAP_KEY
    and   RAP.MEC_KEY = ACT.MEC_KEY
    AND   AP.MAP_KEY = V.MAP_KEY
    AND   EC.MEC_KEY = ACT.MEC_KEY
    AND   PAR.MPAR_KEY = ACT.MPAR_KEY
    AND   S.FSPN_KEY = ACT.FSPN_KEY
    AND   D.FDIP_CODE = S.FDIP_CODE
    AND   H.FSPN_KEY = S.FSPN_KEY
    and   g.fgra_code = D.FGRA_CODE;




-- liste des activites pour un EC de la liste.
-- non liée à des AP.
----------------------------------------------
SELECT GLE.GL_KEY,GLE.MEC_KEY,ACT.ACTIVITE_KEY,TA.LIB_LONG,ACT.NB_HEURES_ACTIVITE,nvl(sum(nvl(V.NB_HEURE_REALISE,V.NB_HEURES_VOEUX)),0) nb_heures_realisees
FROM GRILLE_ENS.GRILLE_LISTE_EC GLE,GRILLE_ENS.ACTIVITE ACT,GRILLE_ENS.TYPE_ACTIVITE TA,GRILLE_ENS.voeux v
WHERE ACT.MEC_KEY = GLE.MEC_KEY
AND   TA.TYPE_ACTIVITE_KEY = ACT.TYPE_ACTIVITE_KEY
AND   V.ACTIVITE_KEY(+) = ACT.ACTIVITE_KEY 
GROUP BY GLE.GL_KEY, GLE.MEC_KEY, ACT.ACTIVITE_KEY, TA.LIB_LONG, ACT.NB_HEURES_ACTIVITE
;


-- liste des enseignements pour un EC de la liste.
-- liée à des AP.
----------------------------------------------
SELECT GLE.GL_KEY,GLE.MEC_KEY,MRAP.MAP_KEY,AP.MAP_LIBELLE,V.NB_HEURES_VOEUX,nvl(V.NB_HEURE_REALISE,v.nb_heures_voeux) NB_HEURE_REALISE
FROM GRILLE_ENS.GRILLE_LISTE_EC GLE,SCOLARITE.SCOL_MAQUETTE_REPARTITION_AP MRAP,scolarite.scol_maquette_ap ap,GRILLE_ENS.VOEUX v
WHERE MRAP.MEC_KEY = GLE.MEC_KEY
AND   V.MAP_KEY = MRAP.MAP_KEY
and   AP.MAP_KEY = v.map_key
;

-- somme à vérifier
SELECT GLE.GL_KEY,GLE.MEC_KEY,MRAP.MAP_KEY,AP.MAP_LIBELLE,V.NB_HEURES_VOEUX,sum(nvl(V.NB_HEURE_REALISE,v.nb_heures_voeux)) NB_HEURE_REALISE
FROM GRILLE_ENS.GRILLE_LISTE_EC GLE,SCOLARITE.SCOL_MAQUETTE_REPARTITION_AP MRAP,scolarite.scol_maquette_ap ap,GRILLE_ENS.VOEUX v
WHERE MRAP.MEC_KEY = GLE.MEC_KEY
AND   V.MAP_KEY = MRAP.MAP_KEY
AND   AP.MAP_KEY = V.MAP_KEY GROUP BY GLE.GL_KEY, GLE.MEC_KEY, MRAP.MAP_KEY, AP.MAP_LIBELLE, V.NB_HEURES_VOEUX
;


-- 
SELECT I.NOM_USUEL,I.PRENOM,ACT.ACTIVITE_KEY
FROM  GRHUM.INDIVIDU_ULR I,GRILLE_ENS.ACTIVITE ACT,GRILLE_ENS.VOEUX V
WHERE I.NO_INDIVIDU = V.NO_INDIVIDU
and   V.ACTIVITE_KEY = ACT.ACTIVITE_KEY;


-- Totaux des réalisés par enseignant et un EC
SELECT I.NOM_USUEL,I.PRENOM,MRAP.MEC_KEY , AP.MHCO_CODE,  SUM(NVL(V.NB_HEURE_REALISE,V.NB_HEURES_VOEUX)) NB_HEURE_REALISE
FROM GRILLE_ENS.VOEUX V,SCOLARITE.SCOL_MAQUETTE_REPARTITION_AP MRAP,SCOLarite.scol_maquette_ap ap,grhum.individu_ulr i
WHERE V.MAP_KEY = MRAP.MAP_KEY
AND   AP.MAP_KEY = V.MAP_KEY
AND   I.NO_INDIVIDU = V.NO_INDIVIDU
GROUP BY I.NOM_USUEL, I.PRENOM, MRAP.MEC_KEY, AP.MHCO_CODE;

-- Totaux réalisés par enseignant et par activités liées à un EC
SELECT ACT.MEC_KEY,i.nom_usuel,i.prenom,TA.LIB_COURT,SUM(NVL(V.NB_HEURE_REALISE,V.NB_HEURES_VOEUX)) NB_HEURE_REALISE
FROM GRILLE_ENS.ACTIVITE ACT,GRILLE_ENS.TYPE_ACTIVITE TA,GRILLE_ENS.VOEUX V,grhum.individu_ulr i
WHERE TA.TYPE_ACTIVITE_KEY = ACT.TYPE_ACTIVITE_KEY
AND V.ACTIVITE_KEY = ACT.ACTIVITE_KEY
AND I.NO_INDIVIDU = V.NO_INDIVIDU 
GROUP BY ACT.MEC_KEY, i.nom_usuel, i.prenom, TA.LIB_COURT
;

